extend type LagValue {
  """
  ✨ Implicit foreign key field based on `LagValue`.`relationship`. It must match the value of `Relationship`.`id`. See `@ref` for how to customize it.
  """
  relationshipId: UUID! @fdc_generated(from: "LagValue.relationship", purpose: IMPLICIT_REF_FIELD)
}
extend type PerspectiveMember {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "PerspectiveMember", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `PerspectiveMember`.`perspective`. It must match the value of `Perspective`.`id`. See `@ref` for how to customize it.
  """
  perspectiveId: UUID! @fdc_generated(from: "PerspectiveMember.perspective", purpose: IMPLICIT_REF_FIELD)
}
extend type Relationship {
  """
  ✨ Implicit foreign key field based on `Relationship`.`contributorStory`. It must match the value of `Story`.`id`. See `@ref` for how to customize it.
  """
  contributorStoryId: UUID! @fdc_generated(from: "Relationship.contributorStory", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Relationship`.`focalStory`. It must match the value of `Story`.`id`. See `@ref` for how to customize it.
  """
  focalStoryId: UUID! @fdc_generated(from: "Relationship.focalStory", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Relationship`.`variant`. It must match the value of `Variant`.`id`. See `@ref` for how to customize it.
  """
  variantId: UUID @fdc_generated(from: "Relationship.variant", purpose: IMPLICIT_REF_FIELD)
}
extend type RelationshipValue {
  """
  ✨ Implicit foreign key field based on `RelationshipValue`.`relationship`. It must match the value of `Relationship`.`id`. See `@ref` for how to customize it.
  """
  relationshipId: UUID! @fdc_generated(from: "RelationshipValue.relationship", purpose: IMPLICIT_REF_FIELD)
}
extend type Story {
  """
  ✨ Implicit foreign key field based on `Story`.`focalTrend`. It must match the value of `Trend`.`id`. See `@ref` for how to customize it.
  """
  focalTrendId: UUID! @fdc_generated(from: "Story.focalTrend", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Story`.`perspective`. It must match the value of `Perspective`.`id`. See `@ref` for how to customize it.
  """
  perspectiveId: UUID! @fdc_generated(from: "Story.perspective", purpose: IMPLICIT_REF_FIELD)
}
extend type Trend {
  """
  ✨ Implicit foreign key field based on `Trend`.`baseTrend`. It must match the value of `Trend`.`id`. See `@ref` for how to customize it.
  """
  baseTrendId: UUID @fdc_generated(from: "Trend.baseTrend", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Trend`.`variant`. It must match the value of `Variant`.`id`. See `@ref` for how to customize it.
  """
  variantId: UUID @fdc_generated(from: "Trend.variant", purpose: IMPLICIT_REF_FIELD)
}
extend type TrendValue {
  """
  ✨ Implicit foreign key field based on `TrendValue`.`trend`. It must match the value of `Trend`.`id`. See `@ref` for how to customize it.
  """
  trendId: UUID! @fdc_generated(from: "TrendValue.trend", purpose: IMPLICIT_REF_FIELD)
}
extend type Variant {
  """
  ✨ Implicit foreign key field based on `Variant`.`story`. It must match the value of `Story`.`id`. See `@ref` for how to customize it.
  """
  storyId: UUID! @fdc_generated(from: "Variant.story", purpose: IMPLICIT_REF_FIELD)
}
extend type Weight {
  """
  ✨ Implicit foreign key field based on `Weight`.`relationship`. It must match the value of `Relationship`.`id`. See `@ref` for how to customize it.
  """
  relationshipId: UUID! @fdc_generated(from: "Weight.relationship", purpose: IMPLICIT_REF_FIELD)
}
