extend type Connection {
  """
  ✨ Implicit foreign key field based on `Connection`.`sourceConnection`. It must match the value of `Connection`.`id`. See `@ref` for how to customize it.
  """
  sourceConnectionId: UUID @fdc_generated(from: "Connection.sourceConnection", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Connection`.`sourceTrend`. It must match the value of `Trend`.`id`. See `@ref` for how to customize it.
  """
  sourceTrendId: UUID @fdc_generated(from: "Connection.sourceTrend", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Connection`.`story`. It must match the value of `Story`.`id`. See `@ref` for how to customize it.
  """
  storyId: UUID! @fdc_generated(from: "Connection.story", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Connection`.`targetConnection`. It must match the value of `Connection`.`id`. See `@ref` for how to customize it.
  """
  targetConnectionId: UUID @fdc_generated(from: "Connection.targetConnection", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Connection`.`targetTrend`. It must match the value of `Trend`.`id`. See `@ref` for how to customize it.
  """
  targetTrendId: UUID @fdc_generated(from: "Connection.targetTrend", purpose: IMPLICIT_REF_FIELD)
}
extend type PerspectiveMember {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "PerspectiveMember", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `PerspectiveMember`.`perspective`. It must match the value of `Perspective`.`id`. See `@ref` for how to customize it.
  """
  perspectiveId: UUID! @fdc_generated(from: "PerspectiveMember.perspective", purpose: IMPLICIT_REF_FIELD)
}
extend type Story {
  """
  ✨ Implicit foreign key field based on `Story`.`focalTrend`. It must match the value of `Trend`.`id`. See `@ref` for how to customize it.
  """
  focalTrendId: UUID! @fdc_generated(from: "Story.focalTrend", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Story`.`perspective`. It must match the value of `Perspective`.`id`. See `@ref` for how to customize it.
  """
  perspectiveId: UUID! @fdc_generated(from: "Story.perspective", purpose: IMPLICIT_REF_FIELD)
}
extend type TrendValue {
  """
  ✨ Implicit foreign key field based on `TrendValue`.`trend`. It must match the value of `Trend`.`id`. See `@ref` for how to customize it.
  """
  trendId: UUID! @fdc_generated(from: "TrendValue.trend", purpose: IMPLICIT_REF_FIELD)
}
extend type Variant {
  """
  ✨ Implicit foreign key field based on `Variant`.`story`. It must match the value of `Story`.`id`. See `@ref` for how to customize it.
  """
  storyId: UUID! @fdc_generated(from: "Variant.story", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Variant`.`trend`. It must match the value of `Trend`.`id`. See `@ref` for how to customize it.
  """
  trendId: UUID! @fdc_generated(from: "Variant.trend", purpose: IMPLICIT_REF_FIELD)
}
extend type VariantValue {
  """
  ✨ Implicit foreign key field based on `VariantValue`.`variant`. It must match the value of `Variant`.`id`. See `@ref` for how to customize it.
  """
  variantId: UUID! @fdc_generated(from: "VariantValue.variant", purpose: IMPLICIT_REF_FIELD)
}
