"""
✨ `LagValue_KeyOutput` returns the primary key fields of table type `LagValue`.

It has the same format as `LagValue_Key`, but is only used as mutation return value.
"""
scalar LagValue_KeyOutput
"""
✨ `Perspective_KeyOutput` returns the primary key fields of table type `Perspective`.

It has the same format as `Perspective_Key`, but is only used as mutation return value.
"""
scalar Perspective_KeyOutput
"""
✨ `PerspectiveMember_KeyOutput` returns the primary key fields of table type `PerspectiveMember`.

It has the same format as `PerspectiveMember_Key`, but is only used as mutation return value.
"""
scalar PerspectiveMember_KeyOutput
"""
✨ `Relationship_KeyOutput` returns the primary key fields of table type `Relationship`.

It has the same format as `Relationship_Key`, but is only used as mutation return value.
"""
scalar Relationship_KeyOutput
"""
✨ `RelationshipValue_KeyOutput` returns the primary key fields of table type `RelationshipValue`.

It has the same format as `RelationshipValue_Key`, but is only used as mutation return value.
"""
scalar RelationshipValue_KeyOutput
"""
✨ `Story_KeyOutput` returns the primary key fields of table type `Story`.

It has the same format as `Story_Key`, but is only used as mutation return value.
"""
scalar Story_KeyOutput
"""
✨ `Trend_KeyOutput` returns the primary key fields of table type `Trend`.

It has the same format as `Trend_Key`, but is only used as mutation return value.
"""
scalar Trend_KeyOutput
"""
✨ `TrendValue_KeyOutput` returns the primary key fields of table type `TrendValue`.

It has the same format as `TrendValue_Key`, but is only used as mutation return value.
"""
scalar TrendValue_KeyOutput
"""
✨ `Variant_KeyOutput` returns the primary key fields of table type `Variant`.

It has the same format as `Variant_Key`, but is only used as mutation return value.
"""
scalar Variant_KeyOutput
"""
✨ `Weight_KeyOutput` returns the primary key fields of table type `Weight`.

It has the same format as `Weight_Key`, but is only used as mutation return value.
"""
scalar Weight_KeyOutput
"""
✨ Generated data input type for table 'LagValue'. It includes all necessary fields for creating or upserting rows into table.
"""
input LagValue_Data {
  """
  ✨ Generated from Field `LagValue`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `LagValue`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `LagValue`.`relationshipId` of type `UUID!`
  """
  relationshipId: UUID
  """
  ✨ `_expr` server value variant of `relationshipId` (✨ Generated from Field `LagValue`.`relationshipId` of type `UUID!`)
  """
  relationshipId_expr: UUID_Expr
  """
  ✨ Generated from Field `LagValue`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Key
  """
  ✨ Generated from Field `LagValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp
  """
  ✨ `_expr` server value variant of `timestamp` (✨ Generated from Field `LagValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `timestamp` (✨ Generated from Field `LagValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `timestamp` (✨ Generated from Field `LagValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `LagValue`.`value` of type `Float!`
  """
  value: Float
  """
  ✨ `_expr` server value variant of `value` (✨ Generated from Field `LagValue`.`value` of type `Float!`)
  """
  value_expr: Float_Expr
  """
  ✨ `_update` server value variant of `value` (✨ Generated from Field `LagValue`.`value` of type `Float!`)
  """
  value_update: [Float_Update!]
}
"""
✨ Generated filter input type for table 'LagValue'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input LagValue_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [LagValue_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: LagValue_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [LagValue_Filter!]
  """
  ✨ Generated from Field `LagValue`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `LagValue`.`relationshipId` of type `UUID!`
  """
  relationshipId: UUID_Filter
  """
  ✨ Generated from Field `LagValue`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Filter
  """
  ✨ Generated from Field `LagValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp_Filter
  """
  ✨ Generated from Field `LagValue`.`value` of type `Float!`
  """
  value: Float_Filter
}
"""
✨ Generated first-row input type for table 'LagValue'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input LagValue_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [LagValue_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: LagValue_Filter
}
"""
✨ Generated having input type for table 'LagValue'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input LagValue_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [LagValue_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: LagValue_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [LagValue_Having!]
  """
  ✨ Generated from Field `LagValue`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `LagValue`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `LagValue`.`relationshipId_count` of type `Int!`
  """
  relationshipId_count: Int_Filter
  """
  ✨ Generated from Field `LagValue`.`timestamp_count` of type `Int!`
  """
  timestamp_count: Int_Filter
  """
  ✨ Generated from Field `LagValue`.`value_count` of type `Int!`
  """
  value_count: Int_Filter
  """
  ✨ Generated from Field `LagValue`.`value_sum` of type `Float`
  """
  value_sum: Float_Filter
  """
  ✨ Generated from Field `LagValue`.`value_avg` of type `Float`
  """
  value_avg: Float_Filter
  """
  ✨ Generated from Field `LagValue`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: Timestamp_Filter
  """
  ✨ Generated from Field `LagValue`.`value_min` of type `Float`
  """
  value_min: Float_Filter
  """
  ✨ Generated from Field `LagValue`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: Timestamp_Filter
  """
  ✨ Generated from Field `LagValue`.`value_max` of type `Float`
  """
  value_max: Float_Filter
}
"""
✨ Generated key input type for table 'LagValue'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input LagValue_Key {
  """
  ✨ Generated from Field `LagValue`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `LagValue`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'LagValue'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input LagValue_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: LagValue_Filter
}
"""
✨ Generated order input type for table 'LagValue'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input LagValue_Order {
  """
  ✨ Generated from Field `LagValue`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`relationshipId` of type `UUID!`
  """
  relationshipId: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Order
  """
  ✨ Generated from Field `LagValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`value` of type `Float!`
  """
  value: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`relationshipId_count` of type `Int!`
  """
  relationshipId_count: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`timestamp_count` of type `Int!`
  """
  timestamp_count: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`value_count` of type `Int!`
  """
  value_count: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`value_sum` of type `Float`
  """
  value_sum: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`value_avg` of type `Float`
  """
  value_avg: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`value_min` of type `Float`
  """
  value_min: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: OrderDirection
  """
  ✨ Generated from Field `LagValue`.`value_max` of type `Float`
  """
  value_max: OrderDirection
}
"""
✨ Generated data input type for table 'Perspective'. It includes all necessary fields for creating or upserting rows into table.
"""
input Perspective_Data {
  """
  ✨ Generated from Field `Perspective`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Perspective`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Perspective`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Perspective`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Perspective`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Perspective`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Perspective`.`createdBy` of type `String!`
  """
  createdBy: String
  """
  ✨ `_expr` server value variant of `createdBy` (✨ Generated from Field `Perspective`.`createdBy` of type `String!`)
  """
  createdBy_expr: String_Expr
  """
  ✨ Generated from Field `Perspective`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Perspective`.`name` of type `String!`)
  """
  name_expr: String_Expr
  """
  ✨ Generated from Field `Perspective`.`plan` of type `String!`
  """
  plan: String
  """
  ✨ `_expr` server value variant of `plan` (✨ Generated from Field `Perspective`.`plan` of type `String!`)
  """
  plan_expr: String_Expr
  """
  ✨ Generated from Field `Perspective`.`slug` of type `String!`
  """
  slug: String
  """
  ✨ `_expr` server value variant of `slug` (✨ Generated from Field `Perspective`.`slug` of type `String!`)
  """
  slug_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Perspective'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Perspective_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Perspective_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Perspective_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Perspective_Filter!]
  """
  ✨ Generated from Field `Perspective`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Perspective`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Perspective`.`createdBy` of type `String!`
  """
  createdBy: String_Filter
  """
  ✨ Generated from Field `Perspective`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Perspective`.`plan` of type `String!`
  """
  plan: String_Filter
  """
  ✨ Generated from Field `Perspective`.`slug` of type `String!`
  """
  slug: String_Filter
  """
  ✨ Generated from Field `Perspective`.`perspectiveMembers_on_perspective` of type `[PerspectiveMember!]!`
  """
  perspectiveMembers_on_perspective: PerspectiveMember_ListFilter
  """
  ✨ Generated from Field `Perspective`.`stories_on_perspective` of type `[Story!]!`
  """
  stories_on_perspective: Story_ListFilter
}
"""
✨ Generated first-row input type for table 'Perspective'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Perspective_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Perspective_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Perspective_Filter
}
"""
✨ Generated having input type for table 'Perspective'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Perspective_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Perspective_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Perspective_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Perspective_Having!]
  """
  ✨ Generated from Field `Perspective`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Perspective`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Perspective`.`createdBy_count` of type `Int!`
  """
  createdBy_count: Int_Filter
  """
  ✨ Generated from Field `Perspective`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Perspective`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Perspective`.`plan_count` of type `Int!`
  """
  plan_count: Int_Filter
  """
  ✨ Generated from Field `Perspective`.`slug_count` of type `Int!`
  """
  slug_count: Int_Filter
  """
  ✨ Generated from Field `Perspective`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Perspective`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Perspective'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Perspective_Key {
  """
  ✨ Generated from Field `Perspective`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Perspective`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Perspective'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Perspective_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Perspective_Filter
}
"""
✨ Generated order input type for table 'Perspective'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Perspective_Order {
  """
  ✨ Generated from Field `Perspective`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`createdBy` of type `String!`
  """
  createdBy: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`plan` of type `String!`
  """
  plan: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`slug` of type `String!`
  """
  slug: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`createdBy_count` of type `Int!`
  """
  createdBy_count: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`plan_count` of type `Int!`
  """
  plan_count: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`slug_count` of type `Int!`
  """
  slug_count: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Perspective`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'PerspectiveMember'. It includes all necessary fields for creating or upserting rows into table.
"""
input PerspectiveMember_Data {
  """
  ✨ Generated from Field `PerspectiveMember`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `PerspectiveMember`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `PerspectiveMember`.`perspectiveId` of type `UUID!`
  """
  perspectiveId: UUID
  """
  ✨ `_expr` server value variant of `perspectiveId` (✨ Generated from Field `PerspectiveMember`.`perspectiveId` of type `UUID!`)
  """
  perspectiveId_expr: UUID_Expr
  """
  ✨ Generated from Field `PerspectiveMember`.`perspective` of type `Perspective!`
  """
  perspective: Perspective_Key
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `PerspectiveMember`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `PerspectiveMember`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `PerspectiveMember`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `PerspectiveMember`.`role` of type `String!`
  """
  role: String
  """
  ✨ `_expr` server value variant of `role` (✨ Generated from Field `PerspectiveMember`.`role` of type `String!`)
  """
  role_expr: String_Expr
  """
  ✨ Generated from Field `PerspectiveMember`.`userId` of type `String!`
  """
  userId: String
  """
  ✨ `_expr` server value variant of `userId` (✨ Generated from Field `PerspectiveMember`.`userId` of type `String!`)
  """
  userId_expr: String_Expr
}
"""
✨ Generated filter input type for table 'PerspectiveMember'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input PerspectiveMember_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [PerspectiveMember_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: PerspectiveMember_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [PerspectiveMember_Filter!]
  """
  ✨ Generated from Field `PerspectiveMember`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`perspectiveId` of type `UUID!`
  """
  perspectiveId: UUID_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`perspective` of type `Perspective!`
  """
  perspective: Perspective_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`role` of type `String!`
  """
  role: String_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`userId` of type `String!`
  """
  userId: String_Filter
}
"""
✨ Generated first-row input type for table 'PerspectiveMember'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input PerspectiveMember_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [PerspectiveMember_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: PerspectiveMember_Filter
}
"""
✨ Generated having input type for table 'PerspectiveMember'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input PerspectiveMember_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [PerspectiveMember_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: PerspectiveMember_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [PerspectiveMember_Having!]
  """
  ✨ Generated from Field `PerspectiveMember`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`perspectiveId_count` of type `Int!`
  """
  perspectiveId_count: Int_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`role_count` of type `Int!`
  """
  role_count: Int_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`userId_count` of type `Int!`
  """
  userId_count: Int_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'PerspectiveMember'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input PerspectiveMember_Key {
  """
  ✨ Generated from Field `PerspectiveMember`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `PerspectiveMember`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'PerspectiveMember'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input PerspectiveMember_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: PerspectiveMember_Filter
}
"""
✨ Generated order input type for table 'PerspectiveMember'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input PerspectiveMember_Order {
  """
  ✨ Generated from Field `PerspectiveMember`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`perspectiveId` of type `UUID!`
  """
  perspectiveId: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`perspective` of type `Perspective!`
  """
  perspective: Perspective_Order
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`role` of type `String!`
  """
  role: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`userId` of type `String!`
  """
  userId: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`perspectiveId_count` of type `Int!`
  """
  perspectiveId_count: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`role_count` of type `Int!`
  """
  role_count: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`userId_count` of type `Int!`
  """
  userId_count: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `PerspectiveMember`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Relationship'. It includes all necessary fields for creating or upserting rows into table.
"""
input Relationship_Data {
  """
  ✨ Generated from Field `Relationship`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Relationship`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Relationship`.`contributorStoryId` of type `UUID!`
  """
  contributorStoryId: UUID
  """
  ✨ `_expr` server value variant of `contributorStoryId` (✨ Generated from Field `Relationship`.`contributorStoryId` of type `UUID!`)
  """
  contributorStoryId_expr: UUID_Expr
  """
  ✨ Generated from Field `Relationship`.`focalStoryId` of type `UUID!`
  """
  focalStoryId: UUID
  """
  ✨ `_expr` server value variant of `focalStoryId` (✨ Generated from Field `Relationship`.`focalStoryId` of type `UUID!`)
  """
  focalStoryId_expr: UUID_Expr
  """
  ✨ Generated from Field `Relationship`.`variantId` of type `UUID`
  """
  variantId: UUID
  """
  ✨ `_expr` server value variant of `variantId` (✨ Generated from Field `Relationship`.`variantId` of type `UUID`)
  """
  variantId_expr: UUID_Expr
  """
  ✨ Generated from Field `Relationship`.`contributorStory` of type `Story!`
  """
  contributorStory: Story_Key
  """
  ✨ Generated from Field `Relationship`.`focalStory` of type `Story!`
  """
  focalStory: Story_Key
  """
  ✨ Generated from Field `Relationship`.`variant` of type `Variant`
  """
  variant: Variant_Key
  """
  ✨ Generated from Field `Relationship`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Relationship`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Relationship`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Relationship`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Relationship`.`createdBy` of type `String!`
  """
  createdBy: String
  """
  ✨ `_expr` server value variant of `createdBy` (✨ Generated from Field `Relationship`.`createdBy` of type `String!`)
  """
  createdBy_expr: String_Expr
  """
  ✨ Generated from Field `Relationship`.`type` of type `String!`
  """
  type: String
  """
  ✨ `_expr` server value variant of `type` (✨ Generated from Field `Relationship`.`type` of type `String!`)
  """
  type_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Relationship'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Relationship_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Relationship_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Relationship_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Relationship_Filter!]
  """
  ✨ Generated from Field `Relationship`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Relationship`.`contributorStoryId` of type `UUID!`
  """
  contributorStoryId: UUID_Filter
  """
  ✨ Generated from Field `Relationship`.`focalStoryId` of type `UUID!`
  """
  focalStoryId: UUID_Filter
  """
  ✨ Generated from Field `Relationship`.`variantId` of type `UUID`
  """
  variantId: UUID_Filter
  """
  ✨ Generated from Field `Relationship`.`contributorStory` of type `Story!`
  """
  contributorStory: Story_Filter
  """
  ✨ Generated from Field `Relationship`.`focalStory` of type `Story!`
  """
  focalStory: Story_Filter
  """
  ✨ Generated from Field `Relationship`.`variant` of type `Variant`
  """
  variant: Variant_Filter
  """
  ✨ Generated from Field `Relationship`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Relationship`.`createdBy` of type `String!`
  """
  createdBy: String_Filter
  """
  ✨ Generated from Field `Relationship`.`type` of type `String!`
  """
  type: String_Filter
  """
  ✨ Generated from Field `Relationship`.`lagValues_on_relationship` of type `[LagValue!]!`
  """
  lagValues_on_relationship: LagValue_ListFilter
  """
  ✨ Generated from Field `Relationship`.`relationshipValues_on_relationship` of type `[RelationshipValue!]!`
  """
  relationshipValues_on_relationship: RelationshipValue_ListFilter
  """
  ✨ Generated from Field `Relationship`.`weights_on_relationship` of type `[Weight!]!`
  """
  weights_on_relationship: Weight_ListFilter
}
"""
✨ Generated first-row input type for table 'Relationship'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Relationship_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Relationship_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Relationship_Filter
}
"""
✨ Generated having input type for table 'Relationship'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Relationship_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Relationship_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Relationship_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Relationship_Having!]
  """
  ✨ Generated from Field `Relationship`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Relationship`.`contributorStoryId_count` of type `Int!`
  """
  contributorStoryId_count: Int_Filter
  """
  ✨ Generated from Field `Relationship`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Relationship`.`createdBy_count` of type `Int!`
  """
  createdBy_count: Int_Filter
  """
  ✨ Generated from Field `Relationship`.`focalStoryId_count` of type `Int!`
  """
  focalStoryId_count: Int_Filter
  """
  ✨ Generated from Field `Relationship`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Relationship`.`type_count` of type `Int!`
  """
  type_count: Int_Filter
  """
  ✨ Generated from Field `Relationship`.`variantId_count` of type `Int!`
  """
  variantId_count: Int_Filter
  """
  ✨ Generated from Field `Relationship`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Relationship`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Relationship'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Relationship_Key {
  """
  ✨ Generated from Field `Relationship`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Relationship`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Relationship'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Relationship_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Relationship_Filter
}
"""
✨ Generated order input type for table 'Relationship'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Relationship_Order {
  """
  ✨ Generated from Field `Relationship`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`contributorStoryId` of type `UUID!`
  """
  contributorStoryId: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`focalStoryId` of type `UUID!`
  """
  focalStoryId: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`variantId` of type `UUID`
  """
  variantId: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`contributorStory` of type `Story!`
  """
  contributorStory: Story_Order
  """
  ✨ Generated from Field `Relationship`.`focalStory` of type `Story!`
  """
  focalStory: Story_Order
  """
  ✨ Generated from Field `Relationship`.`variant` of type `Variant`
  """
  variant: Variant_Order
  """
  ✨ Generated from Field `Relationship`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`createdBy` of type `String!`
  """
  createdBy: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`type` of type `String!`
  """
  type: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`contributorStoryId_count` of type `Int!`
  """
  contributorStoryId_count: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`createdBy_count` of type `Int!`
  """
  createdBy_count: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`focalStoryId_count` of type `Int!`
  """
  focalStoryId_count: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`type_count` of type `Int!`
  """
  type_count: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`variantId_count` of type `Int!`
  """
  variantId_count: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Relationship`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'RelationshipValue'. It includes all necessary fields for creating or upserting rows into table.
"""
input RelationshipValue_Data {
  """
  ✨ Generated from Field `RelationshipValue`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `RelationshipValue`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `RelationshipValue`.`relationshipId` of type `UUID!`
  """
  relationshipId: UUID
  """
  ✨ `_expr` server value variant of `relationshipId` (✨ Generated from Field `RelationshipValue`.`relationshipId` of type `UUID!`)
  """
  relationshipId_expr: UUID_Expr
  """
  ✨ Generated from Field `RelationshipValue`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Key
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp
  """
  ✨ `_expr` server value variant of `timestamp` (✨ Generated from Field `RelationshipValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `timestamp` (✨ Generated from Field `RelationshipValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `timestamp` (✨ Generated from Field `RelationshipValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `RelationshipValue`.`value` of type `Float!`
  """
  value: Float
  """
  ✨ `_expr` server value variant of `value` (✨ Generated from Field `RelationshipValue`.`value` of type `Float!`)
  """
  value_expr: Float_Expr
  """
  ✨ `_update` server value variant of `value` (✨ Generated from Field `RelationshipValue`.`value` of type `Float!`)
  """
  value_update: [Float_Update!]
}
"""
✨ Generated filter input type for table 'RelationshipValue'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input RelationshipValue_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [RelationshipValue_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: RelationshipValue_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [RelationshipValue_Filter!]
  """
  ✨ Generated from Field `RelationshipValue`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`relationshipId` of type `UUID!`
  """
  relationshipId: UUID_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`value` of type `Float!`
  """
  value: Float_Filter
}
"""
✨ Generated first-row input type for table 'RelationshipValue'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input RelationshipValue_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [RelationshipValue_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: RelationshipValue_Filter
}
"""
✨ Generated having input type for table 'RelationshipValue'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input RelationshipValue_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [RelationshipValue_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: RelationshipValue_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [RelationshipValue_Having!]
  """
  ✨ Generated from Field `RelationshipValue`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`relationshipId_count` of type `Int!`
  """
  relationshipId_count: Int_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp_count` of type `Int!`
  """
  timestamp_count: Int_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`value_count` of type `Int!`
  """
  value_count: Int_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`value_sum` of type `Float`
  """
  value_sum: Float_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`value_avg` of type `Float`
  """
  value_avg: Float_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: Timestamp_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`value_min` of type `Float`
  """
  value_min: Float_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: Timestamp_Filter
  """
  ✨ Generated from Field `RelationshipValue`.`value_max` of type `Float`
  """
  value_max: Float_Filter
}
"""
✨ Generated key input type for table 'RelationshipValue'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input RelationshipValue_Key {
  """
  ✨ Generated from Field `RelationshipValue`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `RelationshipValue`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'RelationshipValue'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input RelationshipValue_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: RelationshipValue_Filter
}
"""
✨ Generated order input type for table 'RelationshipValue'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input RelationshipValue_Order {
  """
  ✨ Generated from Field `RelationshipValue`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`relationshipId` of type `UUID!`
  """
  relationshipId: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Order
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`value` of type `Float!`
  """
  value: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`relationshipId_count` of type `Int!`
  """
  relationshipId_count: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp_count` of type `Int!`
  """
  timestamp_count: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`value_count` of type `Int!`
  """
  value_count: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`value_sum` of type `Float`
  """
  value_sum: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`value_avg` of type `Float`
  """
  value_avg: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`value_min` of type `Float`
  """
  value_min: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: OrderDirection
  """
  ✨ Generated from Field `RelationshipValue`.`value_max` of type `Float`
  """
  value_max: OrderDirection
}
"""
✨ Generated data input type for table 'Story'. It includes all necessary fields for creating or upserting rows into table.
"""
input Story_Data {
  """
  ✨ Generated from Field `Story`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Story`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Story`.`focalTrendId` of type `UUID!`
  """
  focalTrendId: UUID
  """
  ✨ `_expr` server value variant of `focalTrendId` (✨ Generated from Field `Story`.`focalTrendId` of type `UUID!`)
  """
  focalTrendId_expr: UUID_Expr
  """
  ✨ Generated from Field `Story`.`perspectiveId` of type `UUID!`
  """
  perspectiveId: UUID
  """
  ✨ `_expr` server value variant of `perspectiveId` (✨ Generated from Field `Story`.`perspectiveId` of type `UUID!`)
  """
  perspectiveId_expr: UUID_Expr
  """
  ✨ Generated from Field `Story`.`focalTrend` of type `Trend!`
  """
  focalTrend: Trend_Key
  """
  ✨ Generated from Field `Story`.`perspective` of type `Perspective!`
  """
  perspective: Perspective_Key
  """
  ✨ Generated from Field `Story`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Story`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Story`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Story`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Story`.`createdBy` of type `String!`
  """
  createdBy: String
  """
  ✨ `_expr` server value variant of `createdBy` (✨ Generated from Field `Story`.`createdBy` of type `String!`)
  """
  createdBy_expr: String_Expr
  """
  ✨ Generated from Field `Story`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Story`.`name` of type `String!`)
  """
  name_expr: String_Expr
  """
  ✨ Generated from Field `Story`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Story`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Story`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `Story`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_update: [Timestamp_Update!]
}
"""
✨ Generated filter input type for table 'Story'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Story_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Story_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Story_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Story_Filter!]
  """
  ✨ Generated from Field `Story`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Story`.`focalTrendId` of type `UUID!`
  """
  focalTrendId: UUID_Filter
  """
  ✨ Generated from Field `Story`.`perspectiveId` of type `UUID!`
  """
  perspectiveId: UUID_Filter
  """
  ✨ Generated from Field `Story`.`focalTrend` of type `Trend!`
  """
  focalTrend: Trend_Filter
  """
  ✨ Generated from Field `Story`.`perspective` of type `Perspective!`
  """
  perspective: Perspective_Filter
  """
  ✨ Generated from Field `Story`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Story`.`createdBy` of type `String!`
  """
  createdBy: String_Filter
  """
  ✨ Generated from Field `Story`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Story`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `Story`.`relationships_on_contributorStory` of type `[Relationship!]!`
  """
  relationships_on_contributorStory: Relationship_ListFilter
  """
  ✨ Generated from Field `Story`.`relationships_on_focalStory` of type `[Relationship!]!`
  """
  relationships_on_focalStory: Relationship_ListFilter
  """
  ✨ Generated from Field `Story`.`variants_on_story` of type `[Variant!]!`
  """
  variants_on_story: Variant_ListFilter
}
"""
✨ Generated first-row input type for table 'Story'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Story_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Story_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Story_Filter
}
"""
✨ Generated having input type for table 'Story'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Story_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Story_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Story_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Story_Having!]
  """
  ✨ Generated from Field `Story`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Story`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Story`.`createdBy_count` of type `Int!`
  """
  createdBy_count: Int_Filter
  """
  ✨ Generated from Field `Story`.`focalTrendId_count` of type `Int!`
  """
  focalTrendId_count: Int_Filter
  """
  ✨ Generated from Field `Story`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Story`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Story`.`perspectiveId_count` of type `Int!`
  """
  perspectiveId_count: Int_Filter
  """
  ✨ Generated from Field `Story`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `Story`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Story`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Story`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Story`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Story'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Story_Key {
  """
  ✨ Generated from Field `Story`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Story`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Story'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Story_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Story_Filter
}
"""
✨ Generated order input type for table 'Story'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Story_Order {
  """
  ✨ Generated from Field `Story`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Story`.`focalTrendId` of type `UUID!`
  """
  focalTrendId: OrderDirection
  """
  ✨ Generated from Field `Story`.`perspectiveId` of type `UUID!`
  """
  perspectiveId: OrderDirection
  """
  ✨ Generated from Field `Story`.`focalTrend` of type `Trend!`
  """
  focalTrend: Trend_Order
  """
  ✨ Generated from Field `Story`.`perspective` of type `Perspective!`
  """
  perspective: Perspective_Order
  """
  ✨ Generated from Field `Story`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Story`.`createdBy` of type `String!`
  """
  createdBy: OrderDirection
  """
  ✨ Generated from Field `Story`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Story`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `Story`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Story`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Story`.`createdBy_count` of type `Int!`
  """
  createdBy_count: OrderDirection
  """
  ✨ Generated from Field `Story`.`focalTrendId_count` of type `Int!`
  """
  focalTrendId_count: OrderDirection
  """
  ✨ Generated from Field `Story`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Story`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Story`.`perspectiveId_count` of type `Int!`
  """
  perspectiveId_count: OrderDirection
  """
  ✨ Generated from Field `Story`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `Story`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Story`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `Story`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Story`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Trend'. It includes all necessary fields for creating or upserting rows into table.
"""
input Trend_Data {
  """
  ✨ Generated from Field `Trend`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Trend`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Trend`.`baseTrendId` of type `UUID`
  """
  baseTrendId: UUID
  """
  ✨ `_expr` server value variant of `baseTrendId` (✨ Generated from Field `Trend`.`baseTrendId` of type `UUID`)
  """
  baseTrendId_expr: UUID_Expr
  """
  ✨ Generated from Field `Trend`.`variantId` of type `UUID`
  """
  variantId: UUID
  """
  ✨ `_expr` server value variant of `variantId` (✨ Generated from Field `Trend`.`variantId` of type `UUID`)
  """
  variantId_expr: UUID_Expr
  """
  ✨ Generated from Field `Trend`.`baseTrend` of type `Trend`
  """
  baseTrend: Trend_Key
  """
  ✨ Generated from Field `Trend`.`variant` of type `Variant`
  """
  variant: Variant_Key
  """
  ✨ Generated from Field `Trend`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Trend`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Trend`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Trend`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Trend`.`createdBy` of type `String!`
  """
  createdBy: String
  """
  ✨ `_expr` server value variant of `createdBy` (✨ Generated from Field `Trend`.`createdBy` of type `String!`)
  """
  createdBy_expr: String_Expr
  """
  ✨ Generated from Field `Trend`.`denomination` of type `Float`
  """
  denomination: Float
  """
  ✨ `_expr` server value variant of `denomination` (✨ Generated from Field `Trend`.`denomination` of type `Float`)
  """
  denomination_expr: Float_Expr
  """
  ✨ `_update` server value variant of `denomination` (✨ Generated from Field `Trend`.`denomination` of type `Float`)
  """
  denomination_update: [Float_Update!]
  """
  ✨ Generated from Field `Trend`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `Trend`.`description` of type `String`)
  """
  description_expr: String_Expr
  """
  ✨ Generated from Field `Trend`.`externalId` of type `String`
  """
  externalId: String
  """
  ✨ `_expr` server value variant of `externalId` (✨ Generated from Field `Trend`.`externalId` of type `String`)
  """
  externalId_expr: String_Expr
  """
  ✨ Generated from Field `Trend`.`frequency` of type `String!`
  """
  frequency: String
  """
  ✨ `_expr` server value variant of `frequency` (✨ Generated from Field `Trend`.`frequency` of type `String!`)
  """
  frequency_expr: String_Expr
  """
  ✨ Generated from Field `Trend`.`name` of type `String!`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Trend`.`name` of type `String!`)
  """
  name_expr: String_Expr
  """
  ✨ Generated from Field `Trend`.`source` of type `String!`
  """
  source: String
  """
  ✨ `_expr` server value variant of `source` (✨ Generated from Field `Trend`.`source` of type `String!`)
  """
  source_expr: String_Expr
  """
  ✨ Generated from Field `Trend`.`unit` of type `String`
  """
  unit: String
  """
  ✨ `_expr` server value variant of `unit` (✨ Generated from Field `Trend`.`unit` of type `String`)
  """
  unit_expr: String_Expr
  """
  ✨ Generated from Field `Trend`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp
  """
  ✨ `_expr` server value variant of `updatedAt` (✨ Generated from Field `Trend`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `updatedAt` (✨ Generated from Field `Trend`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `updatedAt` (✨ Generated from Field `Trend`.`updatedAt` of type `Timestamp!`)
  """
  updatedAt_update: [Timestamp_Update!]
}
"""
✨ Generated filter input type for table 'Trend'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Trend_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Trend_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Trend_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Trend_Filter!]
  """
  ✨ Generated from Field `Trend`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Trend`.`baseTrendId` of type `UUID`
  """
  baseTrendId: UUID_Filter
  """
  ✨ Generated from Field `Trend`.`variantId` of type `UUID`
  """
  variantId: UUID_Filter
  """
  ✨ Generated from Field `Trend`.`baseTrend` of type `Trend`
  """
  baseTrend: Trend_Filter
  """
  ✨ Generated from Field `Trend`.`variant` of type `Variant`
  """
  variant: Variant_Filter
  """
  ✨ Generated from Field `Trend`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Trend`.`createdBy` of type `String!`
  """
  createdBy: String_Filter
  """
  ✨ Generated from Field `Trend`.`denomination` of type `Float`
  """
  denomination: Float_Filter
  """
  ✨ Generated from Field `Trend`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `Trend`.`externalId` of type `String`
  """
  externalId: String_Filter
  """
  ✨ Generated from Field `Trend`.`frequency` of type `String!`
  """
  frequency: String_Filter
  """
  ✨ Generated from Field `Trend`.`name` of type `String!`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Trend`.`source` of type `String!`
  """
  source: String_Filter
  """
  ✨ Generated from Field `Trend`.`unit` of type `String`
  """
  unit: String_Filter
  """
  ✨ Generated from Field `Trend`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: Timestamp_Filter
  """
  ✨ Generated from Field `Trend`.`stories_on_focalTrend` of type `[Story!]!`
  """
  stories_on_focalTrend: Story_ListFilter
  """
  ✨ Generated from Field `Trend`.`trends_on_baseTrend` of type `[Trend!]!`
  """
  trends_on_baseTrend: Trend_ListFilter
  """
  ✨ Generated from Field `Trend`.`trendValues_on_trend` of type `[TrendValue!]!`
  """
  trendValues_on_trend: TrendValue_ListFilter
}
"""
✨ Generated first-row input type for table 'Trend'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Trend_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Trend_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Trend_Filter
}
"""
✨ Generated having input type for table 'Trend'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Trend_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Trend_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Trend_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Trend_Having!]
  """
  ✨ Generated from Field `Trend`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`baseTrendId_count` of type `Int!`
  """
  baseTrendId_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`createdBy_count` of type `Int!`
  """
  createdBy_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`denomination_count` of type `Int!`
  """
  denomination_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`externalId_count` of type `Int!`
  """
  externalId_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`frequency_count` of type `Int!`
  """
  frequency_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`source_count` of type `Int!`
  """
  source_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`unit_count` of type `Int!`
  """
  unit_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`variantId_count` of type `Int!`
  """
  variantId_count: Int_Filter
  """
  ✨ Generated from Field `Trend`.`denomination_sum` of type `Float`
  """
  denomination_sum: Float_Filter
  """
  ✨ Generated from Field `Trend`.`denomination_avg` of type `Float`
  """
  denomination_avg: Float_Filter
  """
  ✨ Generated from Field `Trend`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Trend`.`denomination_min` of type `Float`
  """
  denomination_min: Float_Filter
  """
  ✨ Generated from Field `Trend`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Trend`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
  """
  ✨ Generated from Field `Trend`.`denomination_max` of type `Float`
  """
  denomination_max: Float_Filter
  """
  ✨ Generated from Field `Trend`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Trend'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Trend_Key {
  """
  ✨ Generated from Field `Trend`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Trend`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Trend'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Trend_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Trend_Filter
}
"""
✨ Generated order input type for table 'Trend'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Trend_Order {
  """
  ✨ Generated from Field `Trend`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Trend`.`baseTrendId` of type `UUID`
  """
  baseTrendId: OrderDirection
  """
  ✨ Generated from Field `Trend`.`variantId` of type `UUID`
  """
  variantId: OrderDirection
  """
  ✨ Generated from Field `Trend`.`baseTrend` of type `Trend`
  """
  baseTrend: Trend_Order
  """
  ✨ Generated from Field `Trend`.`variant` of type `Variant`
  """
  variant: Variant_Order
  """
  ✨ Generated from Field `Trend`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Trend`.`createdBy` of type `String!`
  """
  createdBy: OrderDirection
  """
  ✨ Generated from Field `Trend`.`denomination` of type `Float`
  """
  denomination: OrderDirection
  """
  ✨ Generated from Field `Trend`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `Trend`.`externalId` of type `String`
  """
  externalId: OrderDirection
  """
  ✨ Generated from Field `Trend`.`frequency` of type `String!`
  """
  frequency: OrderDirection
  """
  ✨ Generated from Field `Trend`.`name` of type `String!`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Trend`.`source` of type `String!`
  """
  source: OrderDirection
  """
  ✨ Generated from Field `Trend`.`unit` of type `String`
  """
  unit: OrderDirection
  """
  ✨ Generated from Field `Trend`.`updatedAt` of type `Timestamp!`
  """
  updatedAt: OrderDirection
  """
  ✨ Generated from Field `Trend`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`baseTrendId_count` of type `Int!`
  """
  baseTrendId_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`createdBy_count` of type `Int!`
  """
  createdBy_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`denomination_count` of type `Int!`
  """
  denomination_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`externalId_count` of type `Int!`
  """
  externalId_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`frequency_count` of type `Int!`
  """
  frequency_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`source_count` of type `Int!`
  """
  source_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`unit_count` of type `Int!`
  """
  unit_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`updatedAt_count` of type `Int!`
  """
  updatedAt_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`variantId_count` of type `Int!`
  """
  variantId_count: OrderDirection
  """
  ✨ Generated from Field `Trend`.`denomination_sum` of type `Float`
  """
  denomination_sum: OrderDirection
  """
  ✨ Generated from Field `Trend`.`denomination_avg` of type `Float`
  """
  denomination_avg: OrderDirection
  """
  ✨ Generated from Field `Trend`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Trend`.`denomination_min` of type `Float`
  """
  denomination_min: OrderDirection
  """
  ✨ Generated from Field `Trend`.`updatedAt_min` of type `Timestamp`
  """
  updatedAt_min: OrderDirection
  """
  ✨ Generated from Field `Trend`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
  """
  ✨ Generated from Field `Trend`.`denomination_max` of type `Float`
  """
  denomination_max: OrderDirection
  """
  ✨ Generated from Field `Trend`.`updatedAt_max` of type `Timestamp`
  """
  updatedAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'TrendValue'. It includes all necessary fields for creating or upserting rows into table.
"""
input TrendValue_Data {
  """
  ✨ Generated from Field `TrendValue`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `TrendValue`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `TrendValue`.`trendId` of type `UUID!`
  """
  trendId: UUID
  """
  ✨ `_expr` server value variant of `trendId` (✨ Generated from Field `TrendValue`.`trendId` of type `UUID!`)
  """
  trendId_expr: UUID_Expr
  """
  ✨ Generated from Field `TrendValue`.`trend` of type `Trend!`
  """
  trend: Trend_Key
  """
  ✨ Generated from Field `TrendValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp
  """
  ✨ `_expr` server value variant of `timestamp` (✨ Generated from Field `TrendValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `timestamp` (✨ Generated from Field `TrendValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `timestamp` (✨ Generated from Field `TrendValue`.`timestamp` of type `Timestamp!`)
  """
  timestamp_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `TrendValue`.`value` of type `Float!`
  """
  value: Float
  """
  ✨ `_expr` server value variant of `value` (✨ Generated from Field `TrendValue`.`value` of type `Float!`)
  """
  value_expr: Float_Expr
  """
  ✨ `_update` server value variant of `value` (✨ Generated from Field `TrendValue`.`value` of type `Float!`)
  """
  value_update: [Float_Update!]
}
"""
✨ Generated filter input type for table 'TrendValue'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TrendValue_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [TrendValue_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: TrendValue_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [TrendValue_Filter!]
  """
  ✨ Generated from Field `TrendValue`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `TrendValue`.`trendId` of type `UUID!`
  """
  trendId: UUID_Filter
  """
  ✨ Generated from Field `TrendValue`.`trend` of type `Trend!`
  """
  trend: Trend_Filter
  """
  ✨ Generated from Field `TrendValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp_Filter
  """
  ✨ Generated from Field `TrendValue`.`value` of type `Float!`
  """
  value: Float_Filter
}
"""
✨ Generated first-row input type for table 'TrendValue'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input TrendValue_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [TrendValue_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: TrendValue_Filter
}
"""
✨ Generated having input type for table 'TrendValue'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input TrendValue_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [TrendValue_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: TrendValue_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [TrendValue_Having!]
  """
  ✨ Generated from Field `TrendValue`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `TrendValue`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `TrendValue`.`timestamp_count` of type `Int!`
  """
  timestamp_count: Int_Filter
  """
  ✨ Generated from Field `TrendValue`.`trendId_count` of type `Int!`
  """
  trendId_count: Int_Filter
  """
  ✨ Generated from Field `TrendValue`.`value_count` of type `Int!`
  """
  value_count: Int_Filter
  """
  ✨ Generated from Field `TrendValue`.`value_sum` of type `Float`
  """
  value_sum: Float_Filter
  """
  ✨ Generated from Field `TrendValue`.`value_avg` of type `Float`
  """
  value_avg: Float_Filter
  """
  ✨ Generated from Field `TrendValue`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: Timestamp_Filter
  """
  ✨ Generated from Field `TrendValue`.`value_min` of type `Float`
  """
  value_min: Float_Filter
  """
  ✨ Generated from Field `TrendValue`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: Timestamp_Filter
  """
  ✨ Generated from Field `TrendValue`.`value_max` of type `Float`
  """
  value_max: Float_Filter
}
"""
✨ Generated key input type for table 'TrendValue'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input TrendValue_Key {
  """
  ✨ Generated from Field `TrendValue`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `TrendValue`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'TrendValue'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input TrendValue_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: TrendValue_Filter
}
"""
✨ Generated order input type for table 'TrendValue'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input TrendValue_Order {
  """
  ✨ Generated from Field `TrendValue`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`trendId` of type `UUID!`
  """
  trendId: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`trend` of type `Trend!`
  """
  trend: Trend_Order
  """
  ✨ Generated from Field `TrendValue`.`timestamp` of type `Timestamp!`
  """
  timestamp: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`value` of type `Float!`
  """
  value: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`timestamp_count` of type `Int!`
  """
  timestamp_count: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`trendId_count` of type `Int!`
  """
  trendId_count: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`value_count` of type `Int!`
  """
  value_count: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`value_sum` of type `Float`
  """
  value_sum: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`value_avg` of type `Float`
  """
  value_avg: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`value_min` of type `Float`
  """
  value_min: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: OrderDirection
  """
  ✨ Generated from Field `TrendValue`.`value_max` of type `Float`
  """
  value_max: OrderDirection
}
"""
✨ Generated data input type for table 'Variant'. It includes all necessary fields for creating or upserting rows into table.
"""
input Variant_Data {
  """
  ✨ Generated from Field `Variant`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Variant`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Variant`.`storyId` of type `UUID!`
  """
  storyId: UUID
  """
  ✨ `_expr` server value variant of `storyId` (✨ Generated from Field `Variant`.`storyId` of type `UUID!`)
  """
  storyId_expr: UUID_Expr
  """
  ✨ Generated from Field `Variant`.`story` of type `Story!`
  """
  story: Story_Key
  """
  ✨ Generated from Field `Variant`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp
  """
  ✨ `_expr` server value variant of `createdAt` (✨ Generated from Field `Variant`.`createdAt` of type `Timestamp!`)
  """
  createdAt_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `createdAt` (✨ Generated from Field `Variant`.`createdAt` of type `Timestamp!`)
  """
  createdAt_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `createdAt` (✨ Generated from Field `Variant`.`createdAt` of type `Timestamp!`)
  """
  createdAt_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Variant`.`createdBy` of type `String!`
  """
  createdBy: String
  """
  ✨ `_expr` server value variant of `createdBy` (✨ Generated from Field `Variant`.`createdBy` of type `String!`)
  """
  createdBy_expr: String_Expr
  """
  ✨ Generated from Field `Variant`.`name` of type `String`
  """
  name: String
  """
  ✨ `_expr` server value variant of `name` (✨ Generated from Field `Variant`.`name` of type `String`)
  """
  name_expr: String_Expr
}
"""
✨ Generated filter input type for table 'Variant'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Variant_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Variant_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Variant_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Variant_Filter!]
  """
  ✨ Generated from Field `Variant`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Variant`.`storyId` of type `UUID!`
  """
  storyId: UUID_Filter
  """
  ✨ Generated from Field `Variant`.`story` of type `Story!`
  """
  story: Story_Filter
  """
  ✨ Generated from Field `Variant`.`createdAt` of type `Timestamp!`
  """
  createdAt: Timestamp_Filter
  """
  ✨ Generated from Field `Variant`.`createdBy` of type `String!`
  """
  createdBy: String_Filter
  """
  ✨ Generated from Field `Variant`.`name` of type `String`
  """
  name: String_Filter
  """
  ✨ Generated from Field `Variant`.`relationships_on_variant` of type `[Relationship!]!`
  """
  relationships_on_variant: Relationship_ListFilter
  """
  ✨ Generated from Field `Variant`.`trends_on_variant` of type `[Trend!]!`
  """
  trends_on_variant: Trend_ListFilter
}
"""
✨ Generated first-row input type for table 'Variant'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Variant_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Variant_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Variant_Filter
}
"""
✨ Generated having input type for table 'Variant'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Variant_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Variant_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Variant_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Variant_Having!]
  """
  ✨ Generated from Field `Variant`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Variant`.`createdAt_count` of type `Int!`
  """
  createdAt_count: Int_Filter
  """
  ✨ Generated from Field `Variant`.`createdBy_count` of type `Int!`
  """
  createdBy_count: Int_Filter
  """
  ✨ Generated from Field `Variant`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Variant`.`name_count` of type `Int!`
  """
  name_count: Int_Filter
  """
  ✨ Generated from Field `Variant`.`storyId_count` of type `Int!`
  """
  storyId_count: Int_Filter
  """
  ✨ Generated from Field `Variant`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: Timestamp_Filter
  """
  ✨ Generated from Field `Variant`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: Timestamp_Filter
}
"""
✨ Generated key input type for table 'Variant'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Variant_Key {
  """
  ✨ Generated from Field `Variant`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Variant`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Variant'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Variant_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Variant_Filter
}
"""
✨ Generated order input type for table 'Variant'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Variant_Order {
  """
  ✨ Generated from Field `Variant`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Variant`.`storyId` of type `UUID!`
  """
  storyId: OrderDirection
  """
  ✨ Generated from Field `Variant`.`story` of type `Story!`
  """
  story: Story_Order
  """
  ✨ Generated from Field `Variant`.`createdAt` of type `Timestamp!`
  """
  createdAt: OrderDirection
  """
  ✨ Generated from Field `Variant`.`createdBy` of type `String!`
  """
  createdBy: OrderDirection
  """
  ✨ Generated from Field `Variant`.`name` of type `String`
  """
  name: OrderDirection
  """
  ✨ Generated from Field `Variant`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Variant`.`createdAt_count` of type `Int!`
  """
  createdAt_count: OrderDirection
  """
  ✨ Generated from Field `Variant`.`createdBy_count` of type `Int!`
  """
  createdBy_count: OrderDirection
  """
  ✨ Generated from Field `Variant`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Variant`.`name_count` of type `Int!`
  """
  name_count: OrderDirection
  """
  ✨ Generated from Field `Variant`.`storyId_count` of type `Int!`
  """
  storyId_count: OrderDirection
  """
  ✨ Generated from Field `Variant`.`createdAt_min` of type `Timestamp`
  """
  createdAt_min: OrderDirection
  """
  ✨ Generated from Field `Variant`.`createdAt_max` of type `Timestamp`
  """
  createdAt_max: OrderDirection
}
"""
✨ Generated data input type for table 'Weight'. It includes all necessary fields for creating or upserting rows into table.
"""
input Weight_Data {
  """
  ✨ Generated from Field `Weight`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Weight`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
  """
  ✨ Generated from Field `Weight`.`relationshipId` of type `UUID!`
  """
  relationshipId: UUID
  """
  ✨ `_expr` server value variant of `relationshipId` (✨ Generated from Field `Weight`.`relationshipId` of type `UUID!`)
  """
  relationshipId_expr: UUID_Expr
  """
  ✨ Generated from Field `Weight`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Key
  """
  ✨ Generated from Field `Weight`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp
  """
  ✨ `_expr` server value variant of `timestamp` (✨ Generated from Field `Weight`.`timestamp` of type `Timestamp!`)
  """
  timestamp_expr: Timestamp_Expr
  """
  ✨ `_time` server value variant of `timestamp` (✨ Generated from Field `Weight`.`timestamp` of type `Timestamp!`)
  """
  timestamp_time: Timestamp_Relative
  """
  ✨ `_update` server value variant of `timestamp` (✨ Generated from Field `Weight`.`timestamp` of type `Timestamp!`)
  """
  timestamp_update: [Timestamp_Update!]
  """
  ✨ Generated from Field `Weight`.`value` of type `Float!`
  """
  value: Float
  """
  ✨ `_expr` server value variant of `value` (✨ Generated from Field `Weight`.`value` of type `Float!`)
  """
  value_expr: Float_Expr
  """
  ✨ `_update` server value variant of `value` (✨ Generated from Field `Weight`.`value` of type `Float!`)
  """
  value_update: [Float_Update!]
}
"""
✨ Generated filter input type for table 'Weight'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Weight_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Weight_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Weight_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Weight_Filter!]
  """
  ✨ Generated from Field `Weight`.`id` of type `UUID!`
  """
  id: UUID_Filter
  """
  ✨ Generated from Field `Weight`.`relationshipId` of type `UUID!`
  """
  relationshipId: UUID_Filter
  """
  ✨ Generated from Field `Weight`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Filter
  """
  ✨ Generated from Field `Weight`.`timestamp` of type `Timestamp!`
  """
  timestamp: Timestamp_Filter
  """
  ✨ Generated from Field `Weight`.`value` of type `Float!`
  """
  value: Float_Filter
}
"""
✨ Generated first-row input type for table 'Weight'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Weight_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Weight_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Weight_Filter
}
"""
✨ Generated having input type for table 'Weight'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Weight_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Weight_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Weight_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Weight_Having!]
  """
  ✨ Generated from Field `Weight`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Weight`.`id_count` of type `Int!`
  """
  id_count: Int_Filter
  """
  ✨ Generated from Field `Weight`.`relationshipId_count` of type `Int!`
  """
  relationshipId_count: Int_Filter
  """
  ✨ Generated from Field `Weight`.`timestamp_count` of type `Int!`
  """
  timestamp_count: Int_Filter
  """
  ✨ Generated from Field `Weight`.`value_count` of type `Int!`
  """
  value_count: Int_Filter
  """
  ✨ Generated from Field `Weight`.`value_sum` of type `Float`
  """
  value_sum: Float_Filter
  """
  ✨ Generated from Field `Weight`.`value_avg` of type `Float`
  """
  value_avg: Float_Filter
  """
  ✨ Generated from Field `Weight`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: Timestamp_Filter
  """
  ✨ Generated from Field `Weight`.`value_min` of type `Float`
  """
  value_min: Float_Filter
  """
  ✨ Generated from Field `Weight`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: Timestamp_Filter
  """
  ✨ Generated from Field `Weight`.`value_max` of type `Float`
  """
  value_max: Float_Filter
}
"""
✨ Generated key input type for table 'Weight'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Weight_Key {
  """
  ✨ Generated from Field `Weight`.`id` of type `UUID!`
  """
  id: UUID
  """
  ✨ `_expr` server value variant of `id` (✨ Generated from Field `Weight`.`id` of type `UUID!`)
  """
  id_expr: UUID_Expr
}
"""
✨ Generated list filter input type for table 'Weight'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Weight_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Weight_Filter
}
"""
✨ Generated order input type for table 'Weight'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Weight_Order {
  """
  ✨ Generated from Field `Weight`.`id` of type `UUID!`
  """
  id: OrderDirection
  """
  ✨ Generated from Field `Weight`.`relationshipId` of type `UUID!`
  """
  relationshipId: OrderDirection
  """
  ✨ Generated from Field `Weight`.`relationship` of type `Relationship!`
  """
  relationship: Relationship_Order
  """
  ✨ Generated from Field `Weight`.`timestamp` of type `Timestamp!`
  """
  timestamp: OrderDirection
  """
  ✨ Generated from Field `Weight`.`value` of type `Float!`
  """
  value: OrderDirection
  """
  ✨ Generated from Field `Weight`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Weight`.`id_count` of type `Int!`
  """
  id_count: OrderDirection
  """
  ✨ Generated from Field `Weight`.`relationshipId_count` of type `Int!`
  """
  relationshipId_count: OrderDirection
  """
  ✨ Generated from Field `Weight`.`timestamp_count` of type `Int!`
  """
  timestamp_count: OrderDirection
  """
  ✨ Generated from Field `Weight`.`value_count` of type `Int!`
  """
  value_count: OrderDirection
  """
  ✨ Generated from Field `Weight`.`value_sum` of type `Float`
  """
  value_sum: OrderDirection
  """
  ✨ Generated from Field `Weight`.`value_avg` of type `Float`
  """
  value_avg: OrderDirection
  """
  ✨ Generated from Field `Weight`.`timestamp_min` of type `Timestamp`
  """
  timestamp_min: OrderDirection
  """
  ✨ Generated from Field `Weight`.`value_min` of type `Float`
  """
  value_min: OrderDirection
  """
  ✨ Generated from Field `Weight`.`timestamp_max` of type `Timestamp`
  """
  timestamp_max: OrderDirection
  """
  ✨ Generated from Field `Weight`.`value_max` of type `Float`
  """
  value_max: OrderDirection
}
