extend type Mutation {
  """
  ✨ Insert a single `LagValue` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  lagValue_insert(
    """
    Data object to insert into the table.
    """
    data: LagValue_Data!
  ): LagValue_KeyOutput! @fdc_generated(from: "LagValue", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Perspective` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  perspective_insert(
    """
    Data object to insert into the table.
    """
    data: Perspective_Data!
  ): Perspective_KeyOutput! @fdc_generated(from: "Perspective", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `PerspectiveMember` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  perspectiveMember_insert(
    """
    Data object to insert into the table.
    """
    data: PerspectiveMember_Data!
  ): PerspectiveMember_KeyOutput! @fdc_generated(from: "PerspectiveMember", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Relationship` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  relationship_insert(
    """
    Data object to insert into the table.
    """
    data: Relationship_Data!
  ): Relationship_KeyOutput! @fdc_generated(from: "Relationship", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `RelationshipValue` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  relationshipValue_insert(
    """
    Data object to insert into the table.
    """
    data: RelationshipValue_Data!
  ): RelationshipValue_KeyOutput! @fdc_generated(from: "RelationshipValue", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Story` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  story_insert(
    """
    Data object to insert into the table.
    """
    data: Story_Data!
  ): Story_KeyOutput! @fdc_generated(from: "Story", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Trend` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  trend_insert(
    """
    Data object to insert into the table.
    """
    data: Trend_Data!
  ): Trend_KeyOutput! @fdc_generated(from: "Trend", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `TrendValue` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  trendValue_insert(
    """
    Data object to insert into the table.
    """
    data: TrendValue_Data!
  ): TrendValue_KeyOutput! @fdc_generated(from: "TrendValue", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Variant` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  variant_insert(
    """
    Data object to insert into the table.
    """
    data: Variant_Data!
  ): Variant_KeyOutput! @fdc_generated(from: "Variant", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Weight` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  weight_insert(
    """
    Data object to insert into the table.
    """
    data: Weight_Data!
  ): Weight_KeyOutput! @fdc_generated(from: "Weight", purpose: INSERT_SINGLE)
  """
  ✨ Insert `LagValue` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  lagValue_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [LagValue_Data!]!
  ): [LagValue_KeyOutput!]! @fdc_generated(from: "LagValue", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Perspective` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  perspective_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Perspective_Data!]!
  ): [Perspective_KeyOutput!]! @fdc_generated(from: "Perspective", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `PerspectiveMember` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  perspectiveMember_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [PerspectiveMember_Data!]!
  ): [PerspectiveMember_KeyOutput!]! @fdc_generated(from: "PerspectiveMember", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Relationship` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  relationship_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Relationship_Data!]!
  ): [Relationship_KeyOutput!]! @fdc_generated(from: "Relationship", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `RelationshipValue` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  relationshipValue_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [RelationshipValue_Data!]!
  ): [RelationshipValue_KeyOutput!]! @fdc_generated(from: "RelationshipValue", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Story` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  story_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Story_Data!]!
  ): [Story_KeyOutput!]! @fdc_generated(from: "Story", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Trend` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  trend_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Trend_Data!]!
  ): [Trend_KeyOutput!]! @fdc_generated(from: "Trend", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `TrendValue` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  trendValue_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [TrendValue_Data!]!
  ): [TrendValue_KeyOutput!]! @fdc_generated(from: "TrendValue", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Variant` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  variant_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Variant_Data!]!
  ): [Variant_KeyOutput!]! @fdc_generated(from: "Variant", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Weight` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  weight_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Weight_Data!]!
  ): [Weight_KeyOutput!]! @fdc_generated(from: "Weight", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `LagValue` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LagValue`.
  """
  lagValue_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: LagValue_Data!
  ): LagValue_KeyOutput! @fdc_generated(from: "LagValue", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Perspective` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Perspective`.
  """
  perspective_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Perspective_Data!
  ): Perspective_KeyOutput! @fdc_generated(from: "Perspective", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `PerspectiveMember` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PerspectiveMember`.
  """
  perspectiveMember_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: PerspectiveMember_Data!
  ): PerspectiveMember_KeyOutput! @fdc_generated(from: "PerspectiveMember", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Relationship` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Relationship`.
  """
  relationship_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Relationship_Data!
  ): Relationship_KeyOutput! @fdc_generated(from: "Relationship", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `RelationshipValue` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `RelationshipValue`.
  """
  relationshipValue_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: RelationshipValue_Data!
  ): RelationshipValue_KeyOutput! @fdc_generated(from: "RelationshipValue", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Story` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Story`.
  """
  story_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Story_Data!
  ): Story_KeyOutput! @fdc_generated(from: "Story", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Trend` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Trend`.
  """
  trend_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Trend_Data!
  ): Trend_KeyOutput! @fdc_generated(from: "Trend", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `TrendValue` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TrendValue`.
  """
  trendValue_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: TrendValue_Data!
  ): TrendValue_KeyOutput! @fdc_generated(from: "TrendValue", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Variant` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Variant`.
  """
  variant_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Variant_Data!
  ): Variant_KeyOutput! @fdc_generated(from: "Variant", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Weight` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Weight`.
  """
  weight_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Weight_Data!
  ): Weight_KeyOutput! @fdc_generated(from: "Weight", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `LagValue` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `LagValue`.
  """
  lagValue_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [LagValue_Data!]!
  ): [LagValue_KeyOutput!]! @fdc_generated(from: "LagValue", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Perspective` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Perspective`.
  """
  perspective_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Perspective_Data!]!
  ): [Perspective_KeyOutput!]! @fdc_generated(from: "Perspective", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `PerspectiveMember` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `PerspectiveMember`.
  """
  perspectiveMember_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [PerspectiveMember_Data!]!
  ): [PerspectiveMember_KeyOutput!]! @fdc_generated(from: "PerspectiveMember", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Relationship` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Relationship`.
  """
  relationship_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Relationship_Data!]!
  ): [Relationship_KeyOutput!]! @fdc_generated(from: "Relationship", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `RelationshipValue` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `RelationshipValue`.
  """
  relationshipValue_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [RelationshipValue_Data!]!
  ): [RelationshipValue_KeyOutput!]! @fdc_generated(from: "RelationshipValue", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Story` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Story`.
  """
  story_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Story_Data!]!
  ): [Story_KeyOutput!]! @fdc_generated(from: "Story", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Trend` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Trend`.
  """
  trend_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Trend_Data!]!
  ): [Trend_KeyOutput!]! @fdc_generated(from: "Trend", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `TrendValue` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `TrendValue`.
  """
  trendValue_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [TrendValue_Data!]!
  ): [TrendValue_KeyOutput!]! @fdc_generated(from: "TrendValue", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Variant` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Variant`.
  """
  variant_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Variant_Data!]!
  ): [Variant_KeyOutput!]! @fdc_generated(from: "Variant", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Weight` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Weight`.
  """
  weight_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Weight_Data!]!
  ): [Weight_KeyOutput!]! @fdc_generated(from: "Weight", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `LagValue` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `LagValue` or `null` if not found.
  """
  lagValue_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LagValue_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LagValue_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: LagValue_Data!
  ): LagValue_KeyOutput @fdc_generated(from: "LagValue", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Perspective` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Perspective` or `null` if not found.
  """
  perspective_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Perspective_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Perspective_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Perspective_Data!
  ): Perspective_KeyOutput @fdc_generated(from: "Perspective", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `PerspectiveMember` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `PerspectiveMember` or `null` if not found.
  """
  perspectiveMember_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PerspectiveMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PerspectiveMember_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: PerspectiveMember_Data!
  ): PerspectiveMember_KeyOutput @fdc_generated(from: "PerspectiveMember", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Relationship` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Relationship` or `null` if not found.
  """
  relationship_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Relationship_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Relationship_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Relationship_Data!
  ): Relationship_KeyOutput @fdc_generated(from: "Relationship", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `RelationshipValue` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `RelationshipValue` or `null` if not found.
  """
  relationshipValue_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: RelationshipValue_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RelationshipValue_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: RelationshipValue_Data!
  ): RelationshipValue_KeyOutput @fdc_generated(from: "RelationshipValue", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Story` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Story` or `null` if not found.
  """
  story_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Story_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Story_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Story_Data!
  ): Story_KeyOutput @fdc_generated(from: "Story", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Trend` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Trend` or `null` if not found.
  """
  trend_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Trend_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Trend_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Trend_Data!
  ): Trend_KeyOutput @fdc_generated(from: "Trend", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `TrendValue` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `TrendValue` or `null` if not found.
  """
  trendValue_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TrendValue_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TrendValue_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: TrendValue_Data!
  ): TrendValue_KeyOutput @fdc_generated(from: "TrendValue", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Variant` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Variant` or `null` if not found.
  """
  variant_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Variant_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Variant_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Variant_Data!
  ): Variant_KeyOutput @fdc_generated(from: "Variant", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Weight` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Weight` or `null` if not found.
  """
  weight_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Weight_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Weight_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Weight_Data!
  ): Weight_KeyOutput @fdc_generated(from: "Weight", purpose: UPDATE_SINGLE)
  """
  ✨ Update `LagValue` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  lagValue_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: LagValue_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: LagValue_Data!
  ): Int! @fdc_generated(from: "LagValue", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Perspective` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  perspective_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Perspective_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Perspective_Data!
  ): Int! @fdc_generated(from: "Perspective", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `PerspectiveMember` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  perspectiveMember_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: PerspectiveMember_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: PerspectiveMember_Data!
  ): Int! @fdc_generated(from: "PerspectiveMember", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Relationship` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  relationship_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Relationship_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Relationship_Data!
  ): Int! @fdc_generated(from: "Relationship", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `RelationshipValue` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  relationshipValue_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: RelationshipValue_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: RelationshipValue_Data!
  ): Int! @fdc_generated(from: "RelationshipValue", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Story` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  story_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Story_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Story_Data!
  ): Int! @fdc_generated(from: "Story", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Trend` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  trend_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Trend_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Trend_Data!
  ): Int! @fdc_generated(from: "Trend", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `TrendValue` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  trendValue_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: TrendValue_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: TrendValue_Data!
  ): Int! @fdc_generated(from: "TrendValue", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Variant` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  variant_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Variant_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Variant_Data!
  ): Int! @fdc_generated(from: "Variant", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Weight` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  weight_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Weight_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Weight_Data!
  ): Int! @fdc_generated(from: "Weight", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `LagValue` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  lagValue_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: LagValue_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: LagValue_FirstRow
  ): LagValue_KeyOutput @fdc_generated(from: "LagValue", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Perspective` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  perspective_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Perspective_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Perspective_FirstRow
  ): Perspective_KeyOutput @fdc_generated(from: "Perspective", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `PerspectiveMember` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  perspectiveMember_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: PerspectiveMember_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: PerspectiveMember_FirstRow
  ): PerspectiveMember_KeyOutput @fdc_generated(from: "PerspectiveMember", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Relationship` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  relationship_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Relationship_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Relationship_FirstRow
  ): Relationship_KeyOutput @fdc_generated(from: "Relationship", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `RelationshipValue` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  relationshipValue_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: RelationshipValue_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RelationshipValue_FirstRow
  ): RelationshipValue_KeyOutput @fdc_generated(from: "RelationshipValue", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Story` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  story_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Story_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Story_FirstRow
  ): Story_KeyOutput @fdc_generated(from: "Story", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Trend` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  trend_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Trend_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Trend_FirstRow
  ): Trend_KeyOutput @fdc_generated(from: "Trend", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `TrendValue` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  trendValue_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: TrendValue_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: TrendValue_FirstRow
  ): TrendValue_KeyOutput @fdc_generated(from: "TrendValue", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Variant` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  variant_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Variant_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Variant_FirstRow
  ): Variant_KeyOutput @fdc_generated(from: "Variant", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Weight` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  weight_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Weight_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Weight_FirstRow
  ): Weight_KeyOutput @fdc_generated(from: "Weight", purpose: DELETE_SINGLE)
  """
  ✨ Delete `LagValue` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  lagValue_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: LagValue_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "LagValue", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Perspective` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  perspective_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Perspective_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Perspective", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `PerspectiveMember` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  perspectiveMember_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: PerspectiveMember_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "PerspectiveMember", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Relationship` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  relationship_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Relationship_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Relationship", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `RelationshipValue` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  relationshipValue_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: RelationshipValue_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "RelationshipValue", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Story` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  story_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Story_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Story", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Trend` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  trend_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Trend_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Trend", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `TrendValue` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  trendValue_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: TrendValue_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "TrendValue", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Variant` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  variant_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Variant_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Variant", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Weight` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  weight_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Weight_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Weight", purpose: DELETE_MULTIPLE)
}
