extend type LagValue {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "LagValue", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `LagValue` table.
  """
  _count: Int! @fdc_generated(from: "LagValue.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `LagValue` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "LagValue.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `LagValue` table where the `relationshipId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  relationshipId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "LagValue.relationshipId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `LagValue` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "LagValue.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `LagValue` table where the `value` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  value_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "LagValue.value", purpose: QUERY_COUNT)
  """
  ✨ Sum the `value` field in the `LagValue` table.
  """
  value_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "LagValue.value", purpose: QUERY_SUM)
  """
  ✨ Average the `value` field in the `LagValue` table.
  """
  value_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "LagValue.value", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `timestamp` field in the `LagValue` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "LagValue.timestamp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `value` field in the `LagValue` table.
  """
  value_min: Float @fdc_generated(from: "LagValue.value", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `LagValue` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "LagValue.timestamp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `value` field in the `LagValue` table.
  """
  value_max: Float @fdc_generated(from: "LagValue.value", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "LagValue.id", purpose: ENTITY_ID)
}
extend type Perspective {
  """
  ✨ List `PerspectiveMember` objects in a one-to-many relationship (where `PerspectiveMember`.`perspective` is this object).
  """
  perspectiveMembers_on_perspective(
    """
    Filter condition to narrow down the query results.
    """
    where: PerspectiveMember_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [PerspectiveMember_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: PerspectiveMember_Having
  ): [PerspectiveMember!]! @fdc_generated(from: "PerspectiveMember.perspective", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Story` objects in a one-to-many relationship (where `Story`.`perspective` is this object).
  """
  stories_on_perspective(
    """
    Filter condition to narrow down the query results.
    """
    where: Story_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Story_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Story_Having
  ): [Story!]! @fdc_generated(from: "Story.perspective", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Perspective", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Perspective` table.
  """
  _count: Int! @fdc_generated(from: "Perspective.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Perspective` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Perspective.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Perspective` table where the `createdBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Perspective.createdBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Perspective` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Perspective.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Perspective` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Perspective.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Perspective` table where the `plan` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  plan_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Perspective.plan", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Perspective` table where the `slug` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  slug_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Perspective.slug", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Perspective` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Perspective.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Perspective` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Perspective.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Perspective.id", purpose: ENTITY_ID)
}
extend type PerspectiveMember {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "PerspectiveMember", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `PerspectiveMember` table.
  """
  _count: Int! @fdc_generated(from: "PerspectiveMember.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PerspectiveMember` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PerspectiveMember.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PerspectiveMember` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PerspectiveMember.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PerspectiveMember` table where the `perspectiveId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  perspectiveId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PerspectiveMember.perspectiveId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PerspectiveMember` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PerspectiveMember.role", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `PerspectiveMember` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "PerspectiveMember.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `PerspectiveMember` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "PerspectiveMember.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `PerspectiveMember` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "PerspectiveMember.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "PerspectiveMember.id", purpose: ENTITY_ID)
}
extend type Relationship {
  """
  ✨ List `LagValue` objects in a one-to-many relationship (where `LagValue`.`relationship` is this object).
  """
  lagValues_on_relationship(
    """
    Filter condition to narrow down the query results.
    """
    where: LagValue_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [LagValue_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: LagValue_Having
  ): [LagValue!]! @fdc_generated(from: "LagValue.relationship", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `RelationshipValue` objects in a one-to-many relationship (where `RelationshipValue`.`relationship` is this object).
  """
  relationshipValues_on_relationship(
    """
    Filter condition to narrow down the query results.
    """
    where: RelationshipValue_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [RelationshipValue_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: RelationshipValue_Having
  ): [RelationshipValue!]! @fdc_generated(from: "RelationshipValue.relationship", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Weight` objects in a one-to-many relationship (where `Weight`.`relationship` is this object).
  """
  weights_on_relationship(
    """
    Filter condition to narrow down the query results.
    """
    where: Weight_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Weight_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Weight_Having
  ): [Weight!]! @fdc_generated(from: "Weight.relationship", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Relationship", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Relationship` table.
  """
  _count: Int! @fdc_generated(from: "Relationship.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Relationship` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Relationship.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Relationship` table where the `createdBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Relationship.createdBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Relationship` table where the `focalStoryId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  focalStoryId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Relationship.focalStoryId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Relationship` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Relationship.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Relationship` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Relationship.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Relationship` table where the `trendId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  trendId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Relationship.trendId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Relationship` table where the `type` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  type_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Relationship.type", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Relationship` table where the `variantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  variantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Relationship.variantId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Relationship` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Relationship.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Relationship` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Relationship.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Relationship.id", purpose: ENTITY_ID)
}
extend type RelationshipValue {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "RelationshipValue", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `RelationshipValue` table.
  """
  _count: Int! @fdc_generated(from: "RelationshipValue.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `RelationshipValue` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "RelationshipValue.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `RelationshipValue` table where the `relationshipId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  relationshipId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "RelationshipValue.relationshipId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `RelationshipValue` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "RelationshipValue.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `RelationshipValue` table where the `value` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  value_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "RelationshipValue.value", purpose: QUERY_COUNT)
  """
  ✨ Sum the `value` field in the `RelationshipValue` table.
  """
  value_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "RelationshipValue.value", purpose: QUERY_SUM)
  """
  ✨ Average the `value` field in the `RelationshipValue` table.
  """
  value_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "RelationshipValue.value", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `timestamp` field in the `RelationshipValue` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "RelationshipValue.timestamp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `value` field in the `RelationshipValue` table.
  """
  value_min: Float @fdc_generated(from: "RelationshipValue.value", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `RelationshipValue` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "RelationshipValue.timestamp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `value` field in the `RelationshipValue` table.
  """
  value_max: Float @fdc_generated(from: "RelationshipValue.value", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "RelationshipValue.id", purpose: ENTITY_ID)
}
extend type Story {
  """
  ✨ List `Relationship` objects in a one-to-many relationship (where `Relationship`.`focalStory` is this object).
  """
  relationships_on_focalStory(
    """
    Filter condition to narrow down the query results.
    """
    where: Relationship_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Relationship_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Relationship_Having
  ): [Relationship!]! @fdc_generated(from: "Relationship.focalStory", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Variant` objects in a one-to-many relationship (where `Variant`.`story` is this object).
  """
  variants_on_story(
    """
    Filter condition to narrow down the query results.
    """
    where: Variant_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Variant_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Variant_Having
  ): [Variant!]! @fdc_generated(from: "Variant.story", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Story", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Story` table.
  """
  _count: Int! @fdc_generated(from: "Story.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Story` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Story.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Story` table where the `createdBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Story.createdBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Story` table where the `focalTrendId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  focalTrendId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Story.focalTrendId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Story` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Story.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Story` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Story.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Story` table where the `perspectiveId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  perspectiveId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Story.perspectiveId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Story` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Story.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Story` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Story.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Story` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Story.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Story` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Story.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Story` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Story.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Story.id", purpose: ENTITY_ID)
}
extend type Trend {
  """
  ✨ List `Relationship` objects in a one-to-many relationship (where `Relationship`.`trend` is this object).
  """
  relationships_on_trend(
    """
    Filter condition to narrow down the query results.
    """
    where: Relationship_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Relationship_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Relationship_Having
  ): [Relationship!]! @fdc_generated(from: "Relationship.trend", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Story` objects in a one-to-many relationship (where `Story`.`focalTrend` is this object).
  """
  stories_on_focalTrend(
    """
    Filter condition to narrow down the query results.
    """
    where: Story_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Story_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Story_Having
  ): [Story!]! @fdc_generated(from: "Story.focalTrend", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Trend` objects in a one-to-many relationship (where `Trend`.`baseTrend` is this object).
  """
  trends_on_baseTrend(
    """
    Filter condition to narrow down the query results.
    """
    where: Trend_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Trend_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Trend_Having
  ): [Trend!]! @fdc_generated(from: "Trend.baseTrend", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `TrendValue` objects in a one-to-many relationship (where `TrendValue`.`trend` is this object).
  """
  trendValues_on_trend(
    """
    Filter condition to narrow down the query results.
    """
    where: TrendValue_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [TrendValue_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: TrendValue_Having
  ): [TrendValue!]! @fdc_generated(from: "TrendValue.trend", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Trend", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Trend` table.
  """
  _count: Int! @fdc_generated(from: "Trend.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `baseTrendId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  baseTrendId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.baseTrendId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `createdBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.createdBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `denomination` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  denomination_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.denomination", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `externalId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  externalId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.externalId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `frequency` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  frequency_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.frequency", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `source` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  source_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.source", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `unit` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  unit_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.unit", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `updatedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  updatedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.updatedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Trend` table where the `variantId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  variantId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Trend.variantId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `denomination` field in the `Trend` table.
  """
  denomination_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Trend.denomination", purpose: QUERY_SUM)
  """
  ✨ Average the `denomination` field in the `Trend` table.
  """
  denomination_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Trend.denomination", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `Trend` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Trend.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `denomination` field in the `Trend` table.
  """
  denomination_min: Float @fdc_generated(from: "Trend.denomination", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `updatedAt` field in the `Trend` table.
  """
  updatedAt_min: Timestamp @fdc_generated(from: "Trend.updatedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Trend` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Trend.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `denomination` field in the `Trend` table.
  """
  denomination_max: Float @fdc_generated(from: "Trend.denomination", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `updatedAt` field in the `Trend` table.
  """
  updatedAt_max: Timestamp @fdc_generated(from: "Trend.updatedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Trend.id", purpose: ENTITY_ID)
}
extend type TrendValue {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "TrendValue", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `TrendValue` table.
  """
  _count: Int! @fdc_generated(from: "TrendValue.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrendValue` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrendValue.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrendValue` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrendValue.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrendValue` table where the `trendId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  trendId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrendValue.trendId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `TrendValue` table where the `value` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  value_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "TrendValue.value", purpose: QUERY_COUNT)
  """
  ✨ Sum the `value` field in the `TrendValue` table.
  """
  value_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "TrendValue.value", purpose: QUERY_SUM)
  """
  ✨ Average the `value` field in the `TrendValue` table.
  """
  value_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "TrendValue.value", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `timestamp` field in the `TrendValue` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "TrendValue.timestamp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `value` field in the `TrendValue` table.
  """
  value_min: Float @fdc_generated(from: "TrendValue.value", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `TrendValue` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "TrendValue.timestamp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `value` field in the `TrendValue` table.
  """
  value_max: Float @fdc_generated(from: "TrendValue.value", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "TrendValue.id", purpose: ENTITY_ID)
}
extend type Variant {
  """
  ✨ List `Relationship` objects in a one-to-many relationship (where `Relationship`.`variant` is this object).
  """
  relationships_on_variant(
    """
    Filter condition to narrow down the query results.
    """
    where: Relationship_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Relationship_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Relationship_Having
  ): [Relationship!]! @fdc_generated(from: "Relationship.variant", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Trend` objects in a one-to-many relationship (where `Trend`.`variant` is this object).
  """
  trends_on_variant(
    """
    Filter condition to narrow down the query results.
    """
    where: Trend_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Trend_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Trend_Having
  ): [Trend!]! @fdc_generated(from: "Trend.variant", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Variant", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Variant` table.
  """
  _count: Int! @fdc_generated(from: "Variant.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Variant` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Variant.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Variant` table where the `createdBy` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdBy_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Variant.createdBy", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Variant` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Variant.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Variant` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Variant.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Variant` table where the `storyId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  storyId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Variant.storyId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Variant` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Variant.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Variant` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Variant.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Variant.id", purpose: ENTITY_ID)
}
extend type Weight {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Weight", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Weight` table.
  """
  _count: Int! @fdc_generated(from: "Weight.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Weight` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Weight.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Weight` table where the `relationshipId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  relationshipId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Weight.relationshipId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Weight` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Weight.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Weight` table where the `value` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  value_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Weight.value", purpose: QUERY_COUNT)
  """
  ✨ Sum the `value` field in the `Weight` table.
  """
  value_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Weight.value", purpose: QUERY_SUM)
  """
  ✨ Average the `value` field in the `Weight` table.
  """
  value_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Weight.value", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `timestamp` field in the `Weight` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "Weight.timestamp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `value` field in the `Weight` table.
  """
  value_min: Float @fdc_generated(from: "Weight.value", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `Weight` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "Weight.timestamp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `value` field in the `Weight` table.
  """
  value_max: Float @fdc_generated(from: "Weight.value", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Weight.id", purpose: ENTITY_ID)
}
